// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7lLPRJBz85Ieefi-RSP9aPz91B2Tge1Y',
    appId: '1:524232872287:web:322552d45536cae82466ea',
    messagingSenderId: '524232872287',
    projectId: 'densihanbai',
    authDomain: 'densihanbai.firebaseapp.com',
    storageBucket: 'densihanbai.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVx5VFQ-4fMqeeC9zOtN2nO_tQWuqmfEI',
    appId: '1:524232872287:android:489411400b2c246b2466ea',
    messagingSenderId: '524232872287',
    projectId: 'densihanbai',
    storageBucket: 'densihanbai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMS3tDuh3M1yul6nKc6eeVxLXWNvq7ek8',
    appId: '1:524232872287:ios:4848204de881878b2466ea',
    messagingSenderId: '524232872287',
    projectId: 'densihanbai',
    storageBucket: 'densihanbai.appspot.com',
    iosBundleId: 'com.example.denshihanbai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMS3tDuh3M1yul6nKc6eeVxLXWNvq7ek8',
    appId: '1:524232872287:ios:92654c8467a5a32d2466ea',
    messagingSenderId: '524232872287',
    projectId: 'densihanbai',
    storageBucket: 'densihanbai.appspot.com',
    iosBundleId: 'com.example.denshihanbai.RunnerTests',
  );
}
